<a href="https://colab.research.google.com/github/chitwan6804/Data_mining/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Loading Data

In [ ]:
#Loading the data
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/pima-indians-diabetes-database")

print("Path to dataset files:", path)

100%|██████████| 8.91k/8.91k [00:00<00:00, 11.5MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/uciml/pima-indians-diabetes-database/versions/1


In [ ]:
import os
print(os.listdir(path))

['diabetes.csv']


In [ ]:
file_path=os.path.join(path,"diabetes.csv")
print(file_path)

/root/.cache/kagglehub/datasets/uciml/pima-indians-diabetes-database/versions/1/diabetes.csv


In [ ]:
import pandas as pd

df=pd.read_csv(file_path)

print(df.head())

print(df.columns)

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')


In [ ]:
array=df.values
print(array)

[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]


## ***Data Transformations***

Scaling

In [ ]:
from numpy import set_printoptions
from sklearn import preprocessing

data_scalar=preprocessing.MinMaxScaler(feature_range=(0,1))
data_rescaled=data_scalar.fit_transform(array)
set_printoptions(precision=3)
print("\nScaled data\n",data_rescaled[0:10])


Scaled data
 [[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483 1.   ]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167 0.   ]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183 1.   ]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.    0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2   1.   ]
 [0.294 0.583 0.607 0.    0.    0.382 0.053 0.15  0.   ]
 [0.176 0.392 0.41  0.323 0.104 0.462 0.073 0.083 1.   ]
 [0.588 0.578 0.    0.    0.    0.526 0.024 0.133 0.   ]
 [0.118 0.99  0.574 0.455 0.642 0.455 0.034 0.533 1.   ]
 [0.471 0.628 0.787 0.    0.    0.    0.066 0.55  1.   ]]


Normalisation

In [ ]:
data_normalizer=preprocessing.Normalizer(norm='l1').fit(array)
data_mormalized=data_normalizer.transform(array)
set_printoptions(precision=2)
print("\nNormalised data\n",data_mormalized[0:3])


Normalised data
 [[0.02 0.43 0.21 0.1  0.   0.1  0.   0.14 0.  ]
 [0.   0.36 0.28 0.12 0.   0.11 0.   0.13 0.  ]
 [0.03 0.59 0.21 0.   0.   0.07 0.   0.1  0.  ]]


In [ ]:
data_normalizer=preprocessing.Normalizer(norm='l2').fit(array)
data_mormalized=data_normalizer.transform(array)
set_printoptions(precision=2)
print("\nNormalised data\n",data_mormalized[0:3])


Normalised data
 [[0.03 0.83 0.4  0.2  0.   0.19 0.   0.28 0.01]
 [0.01 0.72 0.56 0.24 0.   0.22 0.   0.26 0.  ]
 [0.04 0.92 0.32 0.   0.   0.12 0.   0.16 0.01]]


In [ ]:
data_scalar=preprocessing.StandardScaler().fit(array)
data_rescaled=data_scalar.transform(array)
set_printoptions(precision=3)
print("\nScaled data\n",data_rescaled[0:3])


Scaled data
 [[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426  1.366]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191 -0.732]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106  1.366]]


In [ ]:
binarizer = preprocessing.Binarizer(threshold=0.5).fit(array)
Data_binarized = binarizer.transform(array)
print ("\nBinary data:\n", Data_binarized [0:5])


Binary data:
 [[1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 0. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
input_labels=['red','black','red','green','black','yellow','white']
encoder=preprocessing.LabelEncoder()
encoder.fit(input_labels)

LabelEncoder()

In [ ]:
test_labels = ['green','red','black']
encoded_values = encoder.transform(test_labels)
print("\nLabels =", test_labels)
print("Encoded values =", list(encoded_values))
encoded_values = [3,0,4,1]
decoded_list = encoder.inverse_transform(encoded_values)


Labels = ['green', 'red', 'black']
Encoded values = [np.int64(1), np.int64(2), np.int64(0)]


In [ ]:
print("\nEncoded values =", encoded_values)
print("\nDecoded labels =", list(decoded_list))


Encoded values = [3, 0, 4, 1]

Decoded labels = [np.str_('white'), np.str_('black'), np.str_('yellow'), np.str_('green')]


In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# load the dataset
data = load_breast_cancer()

# separate the features and target
X = data.data
y = data.target

# split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# normalize the data using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)