<a href="https://colab.research.google.com/github/chitwan6804/Data_mining/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Numpy***

In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
# print(arr)

arr1=np.array([[10,20],[30,40]])
# print(arr1)

a=np.array([1,2,3,4],dtype=float)
# print(a)

print("Contents of arr:\n",arr);
print("\nContents of arr1:\n",arr1);
print("\nContents of a:\n",a)

print("\nShape:",arr1.shape)
print("\nStrides:",a.strides)

Contents of arr:
 [10 20 30 40 50]

Contents of arr1:
 [[10 20]
 [30 40]]

Contents of a:
 [1. 2. 3. 4.]

Shape: (2, 2)

Strides: (8,)


## ***Data Types***

In [ ]:
dt=np.dtype(np.int32)
print(dt)

int32


In [ ]:
dt=np.dtype([('age',np.int8)])
a=np.array([(10,),(20,)],dtype=dt)
print(a)
print(a['age'])

[(10,) (20,)]
[10 20]


In [ ]:
student=np.dtype([('name','S20'),('age','i1'),('marks','f4')])
a=np.array([('abc',21,50),('xyz',18,75)],dtype=student)
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [ ]:
a=np.array([1,2,3,4,5])
print("Original array:",a)
print("Original Data type:",a.dtype)

a_float=a.astype(np.float32)
print("Converted array:",a_float)
print("Converted dtype:",a_float.dtype)

Original array: [1 2 3 4 5]
Original Data type: int64
Converted array: [1. 2. 3. 4. 5.]
Converted dtype: float32


In [ ]:
a=np.array(['1','2','three','four'])
print("Original array:",a)
print("Original Data type:",a.dtype)

try:
  a_int=a.astype(np.int32)
  print("Converted array:",a_int)
  print("Converted dtype:",a_int.dtype)
except ValueError as e:
  print("Error:",e)

Original array: ['1' '2' 'three' 'four']
Original Data type: <U5
Error: invalid literal for int() with base 10: 'three'


In [ ]:
c=np.array([1+2j,3+4j,5+6j])
print("Original array:",c)
print("Original Data type:",c.dtype)
c_float=c.astype(np.float32)
print("Converted array:",c_float)
print("Converted dtype:",c_float.dtype)

Original array: [1.+2.j 3.+4.j 5.+6.j]
Original Data type: complex128
Converted array: [1. 3. 5.]
Converted dtype: float32


<ipython-input-26-b699bad06b4c>:5: ComplexWarning: Casting complex values to real discards the imaginary part
  c_float=c.astype(np.float32)


In [ ]:
a=np.array([1.1,2.2])
print("Original array:",a)
print("Original Data type:",a.dtype)
def safe_convert(arr,target_type):
  try:
    return arr.astype(target_type)
  except ValueError as e:
    print("Error:",e)
    return None

d_int =safe_convert(a,np.int32)
if d_int is not None:
  print("Converted array:",d_int)
  print("Converted dtype:",d_int.dtype)
else:
  print("Conversion failed")

Original array: [1.1 2.2]
Original Data type: float64
Converted array: [1 2]
Converted dtype: int32


In [ ]:
e=np.array(['1.1','2.2','Three'])
print("Original array:",e)
print("Original Data type:",e.dtype)

def convert_with_nan(arr):
  result=[]
  for item in arr:
    try:
      result.append(float(item))
    except ValueError:
      result.append(np.nan)
  return np.array(result)

e_float=convert_with_nan(e)
print("Converted array:",e_float)
print("Converted dtype:",e_float.dtype)

Original array: ['1.1' '2.2' 'Three']
Original Data type: <U5
Converted array: [1.1 2.2 nan]
Converted dtype: float64


## ***Creating and Manipulating Arrays***

In [ ]:
my_list=[1,2,3,4]
my_array=np.array(my_list)
print("1D Array:\n",my_array)

arr=np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",arr)

arr1=np.zeros(5)
print("1D Array with zeros:\n",arr1)
arr2=np.ones((2,3))
print("2D Array with ones:\n",arr2)
arr3=np.full((2,3),7)
print("2D Array with full:\n",arr3)

arr4=np.eye(3)
print("Identity Matrix:\n",arr4)

array1=np.arange(10)
print("array1:",array1)
array2=np.arange(1,10,2)
print("array2:",array2)

array3=np.linspace(0,1,5)
print("array3:",array3)
array3=np.linspace(0,1,5,endpoint=False)
print("array3:",array3)
array4, step = np.linspace(0, 1, num=5, retstep=True)
print("array3:",array4)
print("Step size:", step)

array5 = np.random.rand(2, 3)
print("array5:\n",array5)

empty_array = np.empty((2, 3))
print("Empty Array:\n",empty_array)

1D Array:
 [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
1D Array with zeros:
 [0. 0. 0. 0. 0.]
2D Array with ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
2D Array with full:
 [[7 7 7]
 [7 7 7]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
array1: [0 1 2 3 4 5 6 7 8 9]
array2: [1 3 5 7 9]
array3: [0.   0.25 0.5  0.75 1.  ]
array3: [0.  0.2 0.4 0.6 0.8]
array3: [0.   0.25 0.5  0.75 1.  ]
Step size: 0.25
array5:
 [[0.88933879 0.69784898 0.62230303]
 [0.04229927 0.69543188 0.96429624]]
Empty Array:
 [[0.88933879 0.69784898 0.62230303]
 [0.04229927 0.69543188 0.96429624]]


## ***Loops***

In [ ]:
# Create a 1-dimensional NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Iterate over the array
for element in arr:
   print(element)

1
2
3
4
5


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Iterate over the array
for row in arr_2d:
   print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]]])

# Iterate over the array
for matrix in arr_3d:
   print(matrix)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
rows,cols=arr_2d.shape

for i in range(rows):
  for j in range(cols):
    print(f"Element at ({i}, {j}): {arr_2d[i, j]}")

Element at (0, 0): 1
Element at (0, 1): 2
Element at (0, 2): 3
Element at (1, 0): 4
Element at (1, 1): 5
Element at (1, 2): 6
Element at (2, 0): 7
Element at (2, 1): 8
Element at (2, 2): 9


In [ ]:
for x in np.nditer(arr_2d):
   print(x)

1
2
3
4
5
6
7
8
9


In [ ]:
for x in np.nditer(arr_2d):
   print(x,end='')

123456789

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Broadcasting addition operation
print("Broadcasting Iteration:")
for x, y in np.nditer([arr1, arr2]):
   print(x + y, end=' ')

Broadcasting Iteration:
5 7 9 

In [ ]:
result=arr1+arr2

In [ ]:
print(result)

[5 7 9]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Broadcasting addition operation
print("Broadcasting Iteration:")
for x, y in np.nditer([arr1, arr2]):
   print(x * y, end=' ')

Broadcasting Iteration:
4 10 18 

The numpy.nditer() function, when used with the external_loop flag, allows iterating through array elements while preserving the array's row structure. This ensures that each row is processed individually, demonstrating how the integrity of dimensions is maintained throughout the iteration process.

In [ ]:
# array with multiple dimensions
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# External loop iteration
print("External Loop:")
for row in np.nditer(arr, flags=['external_loop']):
   print(row)

External Loop:
[1 2 3 4 5 6]


The nditer object has another optional parameter called op_flags. Its default value is read-only, but can be set to read-write or write-only mode. This will enable modifying array elements using this iterator.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Modify array elements
with np.nditer(arr, flags=['buffered'], op_flags=['readwrite']) as it:
   for x in it:
      # Multiply each element by 2
      x[...] = x * 2

print("Modified Array Example:",arr)

Modified Array Example: [ 2  4  6  8 10]


## ***Reshaping***

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((2, 3))
print("Array:\n", arr)
print("Reshaped Array:\n", reshaped_arr)

# Reshaping a 2-D array into a 1-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
reshaped_arr = arr.reshape(-1)
print("Reshaped Array:", reshaped_arr)

arr = np.array([1, 2, 3, 4, 5])
try:
    reshaped_arr = np.reshape(arr, (2, 4))
    print("Reshaped Array:\n", reshaped_arr)
except ValueError as e:
    print("Error Occurred During Reshaping:")
    print(e)

Array:
 [1 2 3 4 5 6]
Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Array:
 [[1 2 3]
 [4 5 6]]
Reshaped Array: [1 2 3 4 5 6]
Error Occurred During Reshaping:
cannot reshape array of size 5 into shape (2,4)


we are reshaping a 2-D array "arr" with shape (2, 3) into a 1-D array using the reshape() function with -1 as the argument −

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape to 1-D array
reshaped_arr = arr.reshape(-1)
print("Reshaped Array:", reshaped_arr)

Reshaped Array: [1 2 3 4 5 6]


In [ ]:
arr=np.array([1,2,3,4,5])
try:
  reshaped_arr=np.reshape(arr,(2,4))
  print("Reshaped Array:\n",reshaped_arr)
except ValueError as e:
  print("Error Occurred During Reshaping:")
  print(e)

Error Occurred During Reshaping:
cannot reshape array of size 5 into shape (2,4)


## ***Concatenation***

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

# Concatenating along axis 0 (rows)
concated_arr = np.concatenate((arr1, arr2), axis=0)
print("Concatenated Array:\n", concated_arr)

# Concatenating along axis 1 (columns)
concated_arr = np.concatenate((arr1, arr2), axis=1)
print("Concatenated Array:\n", concated_arr)

Concatenated Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Concatenated Array:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([[4,5,6],[7,8,9]])

# Expanding dimensions of arr1
expand_arr1 = np.expand_dims(arr1, axis=0)
print("Expanded Array:\n", expand_arr1)

# Concatenating along axis 0
concated_arr = np.concatenate((arr2, expand_arr1), axis=0)
print("Concatenated Array:\n", concated_arr)


Expanded Array:
 [[1 2 3]]
Concatenated Array:
 [[4 5 6]
 [7 8 9]
 [1 2 3]]


In [ ]:
arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

arr3 = np.array([[9, 10],
                 [11, 12]])

# Stacking along a new third axis
result = np.stack((arr1, arr2, arr3), axis=2)
print("Stacked along a new axis:")
print(result)


Stacked along a new axis:
[[[ 1  5  9]
  [ 2  6 10]]

 [[ 3  7 11]
  [ 4  8 12]]]


In [ ]:
# Creating an array for splitting
arr = np.arange(9).reshape(3,3)

# Splitting the array into 3 equal parts along axis 1
split_arr = np.split(arr, 3, axis=1)
print("Splitted Array:\n", split_arr)
# Splitting into unequal sub-arrays
arr = np.arange(10)
split_arr = np.array_split(arr, 3)

print("Original Array:")
print(arr)
print("\nSplit into 3 unequal sub-arrays:")
for sub_arr in split_arr:
   print(sub_arr)


Splitted Array:
 [array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
Original Array:
[0 1 2 3 4 5 6 7 8 9]

Split into 3 unequal sub-arrays:
[0 1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

# Flattening the array
flat_array = arr.flatten()
print("Flattened Array:\n", flat_array)

# Using ravel() to flatten
raveled_arr = arr.ravel()
print("\nRaveled Array:", raveled_arr)


Flattened Array:
 [1 2 3 4 5 6]

Raveled Array: [1 2 3 4 5 6]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

# Transposing a 2D array
transposed_arr = np.transpose(arr)

print("Original Array:")
print(arr)
print("\nTransposed Array:")
print(transposed_arr)
# Transposing a 3D array
arr_3d = np.array([[[1, 2],
                    [3, 4]],
                   [[5, 6],
                    [7, 8]]])

transposed_arr_3d = np.transpose(arr_3d)

print("Original 3D Array:")
print(arr_3d)
print("\nTransposed 3D Array:")
print(transposed_arr_3d)

Original Array:
[[1 2 3]
 [4 5 6]]

Transposed Array:
[[1 4]
 [2 5]
 [3 6]]
Original 3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Transposed 3D Array:
[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]
