<a href="https://colab.research.google.com/github/chitwan6804/Data_mining/blob/main/Pandas_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

Forming Series from data

In [ ]:
data=['Chitwan',20,'Female']
series=pd.Series(data,index=['Name','Age','Gender'])
print("Data is stored as: \n",data)
print("\nSeries is stored as: \n",series)

Data is stored as: 
 ['Chitwan', 20, 'Female']

Series is stored as: 
 Name      Chitwan
Age            20
Gender     Female
dtype: object


Forming dataframe from data

In [ ]:
data={
    'Name': ['Steve','Lia','Vin','Katie'],
    'Age': [32,28,45,38],
    'Gender': ['Male','Female','Male','Female'],
    'Rating': [3.45,4.6,3.9,2.78]
}
df=pd.DataFrame(data)
print("\nDataFrame is stored as: \n",df)


DataFrame is stored as: 
     Name  Age  Gender  Rating
0  Steve   32    Male    3.45
1    Lia   28  Female    4.60
2    Vin   45    Male    3.90
3  Katie   38  Female    2.78


Searching for only names column from the dataframe

In [ ]:
print("Names in the list are as follows:\n");
print(df['Name'])

Names in the list are as follows:

0    Steve
1      Lia
2      Vin
3    Katie
Name: Name, dtype: object


Index types:
(By default it is numerical index)

In [ ]:
print("\nDatafrane Index object Type:",df.index.dtype)


Datafrane Index object Type: int64


In [ ]:
#CategoricalIndex
categories=pd.CategoricalIndex(['a','b','a','d'])
df=pd.DataFrame({'Col1':[1,2,3,4], 'Col2':[5,6,7,8]}, index=categories)
print('Input DataFrame:\n',df)
print("\nDatafrane Index object Type:",df.index.dtype)

Input DataFrame:
    Col1  Col2
a     1     5
b     2     6
a     3     7
d     4     8

Datafrane Index object Type: category


In [ ]:
#IntervalIndex
interval_idx=pd.interval_range(start=1,end=5)
df=pd.DataFrame({'Col1':[1,2,3,4], 'Col2':[5,6,7,8]}, index=interval_idx)
print('Input DataFrame:\n',df)
print("\nDatafrane Index object Type:",df.index.dtype)

Input DataFrame:
         Col1  Col2
(1, 2]     1     5
(2, 3]     2     6
(3, 4]     3     7
(4, 5]     4     8

Datafrane Index object Type: interval[int64, right]


In [ ]:
#Create MultiIndex
arrays=[[1,1,2,2],['red','blue','red','blue']]
multi_idx=pd.MultiIndex.from_arrays(arrays,names=('number','color'))
df=pd.DataFrame({'value1':[1,2,3,4],'value2':[5,6,7,8]},index=multi_idx)
print('Input DataFrame:\n',df)
print("\nDatafrane Index object Type:",df.index.dtype)

Input DataFrame:
               value1  value2
number color                
1      red         1       5
       blue        2       6
2      red         3       7
       blue        4       8

Datafrane Index object Type: object


In [ ]:
#DateTimeIndex
datetime_idx=pd.DatetimeIndex(['2020-01-01 10:00:00','2020-01-01 11:00:00','2020-01-03 10:00:00','2020-01-04 10:00:00'])
df=pd.DataFrame({'value1':[1,2,3,4],'value2':[5,6,7,8]},index=datetime_idx)
print('Input DataFrame:\n',df)
print("\nDatafrane Index object Type:",df.index.dtype)

Input DataFrame:
                      value1  value2
2020-01-01 10:00:00       1       5
2020-01-01 11:00:00       2       6
2020-01-03 10:00:00       3       7
2020-01-04 10:00:00       4       8

Datafrane Index object Type: datetime64[ns]


In [ ]:
#TimedeltaIndex
timedelta_idx=pd.TimedeltaIndex(['1 days','2 days','3 days','4 days'])
df=pd.DataFrame({'value1':[1,2,3,4],'value2':[5,6,7,8]},index=timedelta_idx)
print('Input DataFrame:\n',df)
print("\nDatafrane Index object Type:",df.index.dtype)

Input DataFrame:
         value1  value2
1 days       1       5
2 days       2       6
3 days       3       7
4 days       4       8

Datafrane Index object Type: timedelta64[ns]


In [ ]:
#PeriodIndex
period_idx=pd.PeriodIndex(year=[2020,2021,2022,2024],quarter=[1,2,3,4])
df=pd.DataFrame({'value1':[1,2,3,4],'value2':[5,6,7,8]},index=period_idx)
print('Input DataFrame:\n',df)

Input DataFrame:
         value1  value2
2020Q1       1       5
2021Q2       2       6
2022Q3       3       7
2024Q4       4       8


<ipython-input-24-3237f8699425>:2: FutureWarning: Constructing PeriodIndex from fields is deprecated. Use PeriodIndex.from_fields instead.
  period_idx=pd.PeriodIndex(year=[2020,2021,2022,2024],quarter=[1,2,3,4])


Panel

In [ ]:
#Panel is no longer present in pandas.
#It was removed in pandas version 1.0.0 (released in January 2020).

In [ ]:
import numpy as np
df=pd.DataFrame(np.random.randn(3,4),columns=list('ABCD'))
print("DataFrame:\n",df)

print("Results")
print("\nData types:\n",df.dtypes)
print("\nIndex:",df.index)
print("Columns:",df.columns)
print("Values:\n",df.values)
print("Shape:",df.shape)
print("Dimension:",df.ndim)
print("Size:",df.size)
print("Is empty:",df.empty)

DataFrame:
           A         B         C         D
0  1.024648 -0.772922  1.249594  1.122892
1 -1.472067  0.142523 -0.168313 -1.342314
2  0.401891 -1.116344 -1.512436 -0.219329
Results

Data types:
 A    float64
B    float64
C    float64
D    float64
dtype: object

Index: RangeIndex(start=0, stop=3, step=1)
Columns: Index(['A', 'B', 'C', 'D'], dtype='object')
Values:
 [[ 1.02464776 -0.77292162  1.24959407  1.12289178]
 [-1.47206689  0.14252321 -0.16831344 -1.34231389]
 [ 0.40189144 -1.11634368 -1.51243613 -0.21932926]]
Shape: (3, 4)
Dimension: 2
Size: 12
Is empty: False


In [ ]:
# Create a Series with random numbers
s = pd.Series(np.random.randn(10))

print("Series:")
print(s)

# Using basic methods
print("First 5 elements of the Series:\n", s.head())
print("\nLast 3 elements of the Series:\n", s.tail(3))
print("\nDescriptive statistics of the Series:\n", s.describe())

Series:
0    1.581688
1   -1.635350
2    0.065922
3   -0.728606
4   -0.171563
5    0.484093
6   -0.152595
7    0.785664
8    0.062922
9    0.923179
dtype: float64
First 5 elements of the Series:
 0    1.581688
1   -1.635350
2    0.065922
3   -0.728606
4   -0.171563
dtype: float64

Last 3 elements of the Series:
 7    0.785664
8    0.062922
9    0.923179
dtype: float64

Descriptive statistics of the Series:
 count    10.000000
mean      0.121535
std       0.902106
min      -1.635350
25%      -0.166821
50%       0.064422
75%       0.710271
max       1.581688
dtype: float64


In [ ]:
#Create a Dictionary of series
data = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack']),
   'Age':pd.Series([25,26,25,23,30,29,23]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8])}

#Create a DataFrame
df = pd.DataFrame(data)
print("Our data frame is:\n")
print(df)

# Using basic methods
print("\nFirst 5 rows of the DataFrame:\n", df.head())
print("\nLast 3 rows of the DataFrame:\n", df.tail(3))
print("\nInfo of the DataFrame:")
df.info()
print("\nDescriptive statistics of the DataFrame:\n", df.describe())

Our data frame is:

    Name  Age  Rating
0    Tom   25    4.23
1  James   26    3.24
2  Ricky   25    3.98
3    Vin   23    2.56
4  Steve   30    3.20
5  Smith   29    4.60
6   Jack   23    3.80

First 5 rows of the DataFrame:
     Name  Age  Rating
0    Tom   25    4.23
1  James   26    3.24
2  Ricky   25    3.98
3    Vin   23    2.56
4  Steve   30    3.20

Last 3 rows of the DataFrame:
     Name  Age  Rating
4  Steve   30     3.2
5  Smith   29     4.6
6   Jack   23     3.8

Info of the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    7 non-null      object 
 1   Age     7 non-null      int64  
 2   Rating  7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 300.0+ bytes

Descriptive statistics of the DataFrame:
              Age    Rating
count   7.000000  7.000000
mean   25.857143  3.658571
std     2.734262  0

selects all rows for a specific column using the loc indexer.

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])

print("Original DataFrame:\n", df)

#select all rows for a specific column
print('\nResult:\n',df.loc[:,'A'])

Original DataFrame:
           A         B         C         D
a  0.739292  0.581710  0.820864  0.463438
b  1.074361 -0.969742 -0.481592 -1.180939
c  1.513824  0.607310  0.361186 -0.548067
d -0.759489 -1.241849 -0.812407 -0.551907
e -1.218345 -1.449674 -0.969041 -0.680932
f  0.383369  0.905019 -1.117570 -0.794818
g -0.306485  1.197159 -0.943624 -0.296791
h -0.018573 -0.772291  0.841015  0.236345

Result:
 a    0.739292
b    1.074361
c    1.513824
d   -0.759489
e   -1.218345
f    0.383369
g   -0.306485
h   -0.018573
Name: A, dtype: float64


This example selecting all rows for multiple columns.

In [ ]:
# import the pandas library and aliasing as pd
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])

# Select all rows for multiple columns, say list[]
print(df.loc[:,['A','C']])

          A         C
a -0.495634  0.632147
b -0.126255  0.335489
c  1.623975  0.356916
d -0.342358 -0.695694
e -0.234594 -1.981995
f  0.137929  0.468498
g  0.941971  0.423522
h -0.102664  0.988279


This example selects the specific rows for the specific columns.

In [ ]:
print(df.loc[['a','b','f','h'],['A','C']])

          A         C
a -0.495634  0.632147
b -0.126255  0.335489
f  0.137929  0.468498
h -0.102664  0.988279


The following example selecting a range of rows for all columns using the loc indexer.

In [ ]:
print(df.loc[['a','b','f','h'],:])

          A         B         C         D
a -0.495634 -1.456097  0.632147  0.047109
b -0.126255  1.154266  0.335489  0.741718
f  0.137929 -2.609172  0.468498 -0.346525
h -0.102664  0.496887  0.988279  0.262623


selects 4 rows for the all column using the iloc indexer.

In [ ]:
print('\nResult:\n',df.iloc[:4])


Result:
           A         B         C         D
a -0.495634 -1.456097  0.632147  0.047109
b -0.126255  1.154266  0.335489  0.741718
c  1.623975 -1.269102  0.356916  0.007632
d -0.342358 -0.595550 -0.695694  0.131434


selects the specific data using the integer slicing.

In [ ]:
print(df.iloc[1:5, 2:4])

          C         D
b  0.335489  0.741718
c  0.356916  0.007632
d -0.695694  0.131434
e -1.981995  0.337292


selects the data using the slicing through list of values.

In [ ]:
print(df.iloc[[1, 3, 5], [1, 3]])

          B         D
b  1.154266  0.741718
d -0.595550  0.131434
f -2.609172 -0.346525


how to use the direct indexing with brackets for accessing a single column.

In [ ]:
print(df['A'])
print(df.loc[['a','b','f','h'],:])
print(df.iloc[[1, 3, 5], [1, 3]])

a   -0.495634
b   -0.126255
c    1.623975
d   -0.342358
e   -0.234594
f    0.137929
g    0.941971
h   -0.102664
Name: A, dtype: float64
          A         B         C         D
a -0.495634 -1.456097  0.632147  0.047109
b -0.126255  1.154266  0.335489  0.741718
f  0.137929 -2.609172  0.468498 -0.346525
h -0.102664  0.496887  0.988279  0.262623
          B         D
b  1.154266  0.741718
d -0.595550  0.131434
f -2.609172 -0.346525


selects the multiple columns using the direct indexing.

In [ ]:
print(df[['B','A']])

          B         A
a -0.894255  0.845329
b  1.730405 -1.727416
c  0.526794  0.721076
d -1.097301 -0.471668
e  0.748285 -0.534790
f -0.409792  1.104865
g  0.047547  0.296238
h  0.390316 -0.239156


# Series

In [ ]:
data = np.array(['a','b','c','d'])
s = pd.Series(data,index=[100,101,102,103])
print("Output:\n",s)

Output:
 100    a
101    b
102    c
103    d
dtype: object


In [ ]:
data = {'a' : 0., 'b' : 1., 'c' : 2.}
s = pd.Series(data,index=['b','c','x','a'])
print(s)

b    1.0
c    2.0
x    NaN
a    0.0
dtype: float64


In [ ]:
s = pd.Series(5, index=[0, 1, 2, 3])
print(s)

0    5
1    5
2    5
3    5
dtype: int64


Slicing range of values from a Series

In [ ]:
data=np.array(['a','b','c','d'])
s=pd.Series(data)
print('Original Series:\n',s,sep='\n')

result=s[1:3]

print('Result:\n',result,sep='\n')

Original Series:

0    a
1    b
2    c
3    d
dtype: object
Result:

1    b
2    c
dtype: object


Slicing the First Three Elements from a Series

In [ ]:
result=s[:3]

print('Result:\n',result,sep='\n')

Result:

0    a
1    b
2    c
dtype: object


Slicing the Last Three Elements from a Series

In [ ]:
print(s[-3:])

1    b
2    c
3    d
dtype: object


Slicing Group of elements from a Series using the Labels

In [ ]:
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print('Original Series:\n',s,sep='\n')

result=s[['a','c','d']]

print('Result:\n',result,sep='\n')

Original Series:

a    1
b    2
c    3
d    4
e    5
dtype: int64
Result:

a    1
c    3
d    4
dtype: int64


Slicing First Three Elements using the Labels

In [ ]:
print('Result:\n',s[:'c'],sep='\n')

Result:

a    1
b    2
c    3
dtype: int64


In [ ]:
print('Original Series:\n',s,sep='\n')
s[:2]=[100,200]
print('Result:\n',s,sep='\n')

Original Series:

a    1
b    2
c    3
d    4
e    5
dtype: int64
Result:

a    100
b    200
c      3
d      4
e      5
dtype: int64


Applying Arithmetic operations on Series

In [ ]:
# Apply all Arithmetic Operation and Display the Results
print('\nAddition:\n',s+2)
print('\nSubtraction:\n', s-2)
print('\nMultiplication:\n', s * 2)
print('\nDivision:\n', s/2)
print('\nExponentiation:\n', s**2)
print('\nModulus:\n', s%2)
print('\nFloor Division:\n', s//2)


Addition:
 a    102
b    202
c      5
d      6
e      7
dtype: int64

Subtraction:
 a     98
b    198
c      1
d      2
e      3
dtype: int64

Multiplication:
 a    200
b    400
c      6
d      8
e     10
dtype: int64

Division:
 a     50.0
b    100.0
c      1.5
d      2.0
e      2.5
dtype: float64

Exponentiation:
 a    10000
b    40000
c        9
d       16
e       25
dtype: int64

Modulus:
 a    0
b    0
c    1
d    0
e    1
dtype: int64

Floor Division:
 a     50
b    100
c      1
d      2
e      2
dtype: int64


In [ ]:
s1 = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
s2 = pd.Series([9, 8, 6, 5], index=['x','a','b','c'])

# Apply all Arithmetic Operations and Display the Results
print('\nAddition:\n',s1+s2)
print('\nSubtraction:\n', s1-s2)
print('\nMultiplication:\n', s1 * s2)
print('\nDivision:\n', s1/s2)


Addition:
 a    9.0
b    8.0
c    8.0
d    NaN
e    NaN
x    NaN
dtype: float64

Subtraction:
 a   -7.0
b   -4.0
c   -2.0
d    NaN
e    NaN
x    NaN
dtype: float64

Multiplication:
 a     8.0
b    12.0
c    15.0
d     NaN
e     NaN
x     NaN
dtype: float64

Division:
 a    0.125000
b    0.333333
c    0.600000
d         NaN
e         NaN
x         NaN
dtype: float64


In [ ]:
print(s.dtype, s.shape, s.size, s.index, s.values)

int64 (5,) 5 Index(['a', 'b', 'c', 'd', 'e'], dtype='object') [100 200   3   4   5]


In [ ]:
print(s.to_frame(name='Values'))

   Values
a     100
b     200
c       3
d       4
e       5


Converting to list

In [ ]:
s=pd.Series([1,2,3])
result=s.tolist()
print(result)

[1, 2, 3]


to numpy array

In [ ]:
result=s.to_numpy()
print(result)

[1 2 3]


to dictionary

In [ ]:
s=pd.Series([1,2,3],index=['a','b','c'])
result=s.to_dict()
print(result)

{'a': 1, 'b': 2, 'c': 3}


to dataframe

In [ ]:
result=s.to_frame(name='Numbers')
print(result)

   Numbers
a        1
b        2
c        3


In [ ]:
result=s.to_string()
print(repr(result))

'a    1\nb    2\nc    3'


# Dataframe

In [ ]:
data=[['Alex',10],['Bob',12],['Clarke',13]]
df=pd.DataFrame(data,columns=['Name','Age'])
print(df)

     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13


In [ ]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42


In [ ]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
print(df)

        Name  Age
rank1    Tom   28
rank2   Jack   34
rank3  Steve   29
rank4  Ricky   42


In [ ]:
df = pd.DataFrame({'A': [10, 20], 'B': [30, 40]})
df['C'] = df['A'] + df['B']

print(df)

    A   B   C
0  10  30  40
1  20  40  60


In [ ]:
print(df.describe())  # Summary stats
print(df.T)  # Transpose
print(df * 2)  # Multiply all values

               A          B          C
count   2.000000   2.000000   2.000000
mean   15.000000  35.000000  50.000000
std     7.071068   7.071068  14.142136
min    10.000000  30.000000  40.000000
25%    12.500000  32.500000  45.000000
50%    15.000000  35.000000  50.000000
75%    17.500000  37.500000  55.000000
max    20.000000  40.000000  60.000000
    0   1
A  10  20
B  30  40
C  40  60
    A   B    C
0  20  60   80
1  40  80  120
